apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU19jXzZRTWJtNnNPRjB1bXBfNUVLQG5sdy11bml0ZS1kby11c2VyLTg2Mjg0MDctMC5jLmRiLm9uZGlnaXRhbG9jZWFuLmNvbToyNTA2MC9ubHctdW5pdGU/c3NsbW9kZT1yZXF1aXJlCg==
